nodeLinker: node-modules

npmAuthToken: '${NPM_JS_TOKEN}'

npmPublishAccess: restricted

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: '${NPM_JS_TOKEN}'

npmRegistryServer: 'https://registry.npmjs.org'

pnpMode: loose
